jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: admin
  datasource:
    url: ENC(K01jNbcKIUljwo98YtS9qJ5e3PiC2ioQe97fNSKeJ/k9uTVqIgmicqU4NPOHWZjxRIuML2uFRKAXglsCWOizVDH8vHZwmdHGuGaoomTORvE=)
    username: ENC(XhGT41xwg0J9hSXkV9tPjQ==)
    password: ENC(cOWaniGDoCFEXR9v+wRBVEwsJ5Hg6vQN)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

auth:
  service:
    url: http://auth-service.auth.svc:8080